FROM python:3.12-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install playwright==1.58.0 && \
    playwright install --with-deps chromium

COPY . .

CMD ["python", "manage.py", "browse_site", "--count", "5"]
